#!/bin/sh

# colors
if which tput 1>/dev/null 2>&1
then
RED="$(tput setaf 1 bold)"
GREEN="$(tput setaf 2 bold)"
YELLOW="$(tput setaf 3 bold)"
MAGENTA="$(tput setaf 5 bold)"
NC="$(tput sgr0)"
BLUE="$(tput setaf 14 bold)"
PINK="$(tput setaf 217 bold)"
WHITE="$(tput setaf 7 bold)"
elif ! echo -e 'test' | grep -q "\-e" 1>/dev/null 2>&1
RED="$(echo -e '\e[1;31m')"
GREEN="$(echo -e '\e[1;32m')"
YELLOW="$(echo -e '\e[1;33m')"
MAGENTA="$(echo -e '\e[1;35m')"
NC="$(echo -e '\e[0m')"
BLUE="$(echo -e '\x1b[1;96m')"
PINK="$(echo -e '\x1b[1;38;2;245;169;184m')"
WHITE="$(echo -e '\x1b[1;97m')"
fi

# sysinfo
NAME=$(whoami)@$(uname -n)
OS=$(. /etc/os-release; echo "$PRETTY_NAME" || echo "$NAME")
KERNEL=$(uname -r)
SHELL=$(basename $SHELL)
UPTIME=$(awk -F'( |,|:)+' '{printf "%d hours, %d minutes\n", $1/3600, ($1%3600)/60}' /proc/uptime)
MEMORY=$(free -m | awk 'NR==2{print$3"/"$2"MB"}')
SEPARATOR=$(printf %\*s ${#NAME}|tr ' ' '-')

if [ -z "$1" ]
then cat<<BERRY
${GREEN}      (    ((       ${MAGENTA}${NAME}${GREEN}
    ((  (((  ((     ${SEPARATOR}
    ${RED}###${GREEN}(((((${RED}###     ${RED}OS:${NC}      ${OS}${GREEN}
   ${RED}##${YELLOW}%${RED}#######${YELLOW}%${RED}##    ${RED}Kernel:${NC}  ${KERNEL}${RED}
   ######${YELLOW}%${RED}####${YELLOW}%${RED}#    ${RED}Shell:${NC}   ${SHELL}${RED}
    ##${YELLOW}%${RED}####${YELLOW}%${RED}###     ${RED}Uptime:${NC}  ${UPTIME}${RED}
     ####${YELLOW}%${RED}####      ${RED}Memory:${NC}  ${MEMORY}${RED}
       ##### 
         #${NC}
BERRY
elif [ "$1" = "--trans" ]
then cat<<BERRY
${BLUE}      (    ((${NC}       ${MAGENTA}${NAME}${PINK}
    ((  (((  ((     ${SEPARATOR}
    ###(((((###${NC}     ${RED}OS:${NC}      ${OS}${WHITE}
   ##%#######%##    ${RED}Kernel:${NC}  ${KERNEL}${WHITE}
   ######%####%#${NC}    ${RED}Shell:${NC}   ${SHELL}${PINK}
    ##%####%###     ${RED}Uptime:${NC}  ${UPTIME}${PINK}
     #####%###      ${RED}Memory:${NC}  ${MEMORY}${BLUE}
       #####
         # ${NC}
BERRY
else printf "${RED}ERROR:${NC} Unknown argument: ${1}\nCurrently known arguments: --trans\n";exit 1
fi
